services:

  postgres:
    image: postgis/postgis:14-master
    container_name: ticket_world_postgres
    ports:
      - "5433:5432"
    volumes:
    - /var/ticket_world/database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "ticket_world"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  mysql:
    image: mysql:9.1.0
    container_name: currency_exchange_mysql
    ports:
      - '3306:3306'
    volumes:
      - /var/currency_exchange_service/mysql_data:/var/lib/mysql
    env_file:
      - .envs/.env.dev

    restart: always
    networks:
      - back-tier

  redis:
    image: redis:7.0.4-alpine
    container_name: currency_exchange_redis
    ports:
      - '6379:6379'
    volumes:
      - /var/currency_exchange_service/redis_data:/data
    networks:
      - back-tier

networks:
  back-tier:
    driver: bridge
