services:

  postgres:
    image: postgres:15.3-alpine
    container_name: currency_exchange_postgres
    ports:
      - '5432:5432'
    restart: always
    volumes:
    - /var/currency_exchange_service/database-data:/var/lib/postgresql/data
    env_file:
      - .envs/.env.dev

  redis:
    image: redis:7.0.4-alpine
    container_name: currency_exchange_redis
    ports:
      - '6379:6379'
    volumes:
      - /var/currency_exchange_service/redis_data:/data
    networks:
      - back-tier

networks:
  back-tier:
    driver: bridge
